ascension/urls.py
from django.urls import path
from . import views


app_name = 'ascension'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name='inquiry'),
    path('interest_category_list/', views.InterestCategoryListView.as_view(), name='interest_category_list'),
    path('add_interest_category/', views.AddInterestCategoryView.as_view(), name='add_interest_category'),
    path('delete_interest_category/<int:category_id>/', views.DeleteInterestCategoryView.as_view(), name='delete_interest_category'),
    path('learning_object/category/<int:category_id>/', views.LearningObjectiveListView.as_view(), name='learning_objective_list'),
    path('create_learning_ovjective/<int:category_id>/', views.CreateLearningObjectiveView.as_view(), name='create_learning_objective'),

]

learning/urls.py
from django.urls import path


app_name = 'learning'
urlpatterns = [
    
]

my_study_app2/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import settings_common, settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ascension.urls', 'ascension'), namespace='ascension')),
    path('accounts/', include('allauth.urls')),
    path('ai_support/', include(('ai_support.urls', 'ai_support'), namespace='ai_support')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('learning_test/', include(('learning_test.urls', 'learning_test'), namespace='learning_test')),
    path('analytics/', include(('analytics.urls', 'analytics'), namespace='analytics'))
]

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

ascension/models.py
from django.db import models
from accounts.models import CustomUser


# 学習管理モデル(興味分野、学習目標、学習Topic(Main、Sub)、＃＝関連付け)
# カテゴリ(カテゴリ名)
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


# 興味カテゴリ(カテゴリ名)
class InterestCategory(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


# 中間モデル(#ユーザー名、#興味カテゴリ名)
class UserInterest(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(InterestCategory, on_delete=models.CASCADE)


# 学習目標(#ユーザー名、#興味カテゴリ名、目標タイトル、設定時レベル、目標詳細、総獲得スコア、状態(完・未完)、作成日時)
class LearningObjective(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(InterestCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    level_when_set = models.CharField(max_length=100, blank=True, null=True)
    detail = models.TextField(blank=True, null=True)
    total_score = models.IntegerField(blank=True, null=True, default=0)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.title}'
    

# 学習メイントピック(＃学習目標名、メイントピック名)
class LearningMainTopic(models.Model):
    learning_objective = models.ForeignKey(LearningObjective, on_delete=models.CASCADE, related_name='main_topics')
    title = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.learning_objective.title} - {self.title}'
    

# 学習サブトピック(＃学習目標名、＃メイントピック名、サブトピック名)
class LearningSubTopic(models.Model):
    learning_objective = models.ForeignKey(LearningObjective, on_delete=models.CASCADE, related_name='sub_topics')
    main_topic = models.ForeignKey(LearningMainTopic, on_delete=models.CASCADE, related_name='sub_topics')
    title = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.main_topic} - {self.title}'

ascension/forms.py
import os
from django import forms
from django.core.mail import EmailMessage
from .models import Category, LearningObjective


# 問い合わせ
class InquiryForm(forms.Form):
    name = forms.CharField(label='名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form_control'
        self.fields['name'].widget.attrs['placeholder'] = 'ここに名前を入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form_control'
        self.fields['email'].widget.attrs['placeholder'] = 'ここにメールアドレスを入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form_control'
        self.fields['title'].widget.attrs['placeholder'] = 'ここにタイトルを入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form_control'
        self.fields['message'].widget.attrs['placeholder'] = 'ここにメッセージを入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']
        subject = f'お問合せ {title}'
        message = f'送信者名: {name}\nメールアドレス: {email}\n\nお問合せ内容: \n{message}'
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [os.environ('FROM_EMAIL')]
        if not from_email or not to_list[0]:
            raise ValueError('送信元または送信先のメールアドレスが設定されていません。')
        cc_list = [email] if email else []

        message = EmailMessage(
            subject=subject,
            body=message,
            from_email=from_email,
            to=to_list,
            cc=cc_list
        )


# 興味分野の追加
class AddInterestCategoryForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='追加する興味分野を選択してください。',
        widget=forms.Select(attrs={'class': 'form-select'})
    )


# 学習目標の追加
class CreateLearningObjectiveForm(forms.ModelForm):
    class Meta:
        model = LearningObjective
        fields = ('title', 'level_when_set', 'detail')
        labels = {'title': 'テーマ(必須)',
                  'level_when_set': 'テーマの学習経験',
                  'detail': '詳細'}
        widgets = {
            'title': forms.Textarea(attrs={
                'rows': 1,
                'class': 'form-control',
                'placeholder': '学びたいテーマを入力してください。(例:Python)'
            }),
            'level_when_set': forms.Textarea(attrs={
                'rows': 2,
                'class': 'form-control',
                'placeholder': '学習経験の有無や学習レベルを入力することで、より最適な学習プランを生成できます。'
            }),
            'detail': forms.Textarea(attrs={
                'rows': 6,
                'class': 'form-control',
                'placeholder': '目標レベルなどのテーマに関する詳細を入力することで、より最適な学習プランを生成できます。'
            })
        }

ascension/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView, FormView, ListView, CreateView
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator

from .models import InterestCategory, UserInterest, LearningObjective
from .forms import InquiryForm, AddInterestCategoryForm, CreateLearningObjectiveForm


# TOP画面
class IndexView(TemplateView):
    template_name = 'ascension/index.html'


# 問い合わせフォーム
class InquiryView(FormView):
    template_name = 'ascension/inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('ascension:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        return super().form_valid(form)


# 興味分野リスト画面
class InterestCategoryListView(LoginRequiredMixin, ListView):
    model = InterestCategory
    template_name = 'ascension/interest_category_list.html'

    def get_queryset(self):
        return InterestCategory.objects.prefetch_related('users').filter(users=self.request.user)


# 興味分野の追加
class AddInterestCategoryView(LoginRequiredMixin, FormView):
    form_class = AddInterestCategoryForm
    template_name = 'ascension/add_interest_category.html'
    success_url = reverse_lazy('ascension:interest_category_list')

    def form_valid(self, form):
        # フォームから選択されたカテゴリを取得
        selected_category = form.cleaned_data['category']
        # 興味分野を作成or取得
        interest_category, created = InterestCategory.objects.get_or_create(
            name=selected_category.name
        )
        # 中間モデルに追加
        UserInterest.objects.get_or_create(
            user=self.request.user,
            category=interest_category
        )
        return super().form_valid(form)


# 興味分野の削除(関連付けを削除)
class DeleteInterestCategoryView(LoginRequiredMixin, View):
    # 削除確認画面の表示
    def get(self, request, *args, **kwargs):
        category = get_object_or_404(InterestCategory, id=kwargs['category_id'])
        return render(request, 'ascension/delete_interest_category.html', {'category': category})
    
    # 関連付け削除
    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        # urlから削除するカテゴリを取得
        category = get_object_or_404(InterestCategory, id=kwargs['category_id'])
        # ユーザーとカテゴリの関連付け削除
        if request.user.interests.filter(id=category.id).exists():
            request.user.interests.remove(category)
            messages.success(request, f'{ request.user.username }の興味分野リストから"{category.name}"が削除されました。')
        else:
            messages.success(request, f'"{category.name}"は{ request.user.username}と関連付けられていません。')
        
        return redirect('ascension:interest_category_list')
    

# 学習目標リスト画面
class LearningObjectiveListView(LoginRequiredMixin, ListView):
    model = LearningObjective
    template_name = 'ascension/learning_objective_list.html'
    context_object_name = 'learning_objectives'

    # カテゴリごとの学習目標を取得
    def get_queryset(self):
        category_id = self.kwargs.get('category_id')  # urlからカテゴリidを取得
        return LearningObjective.objects.filter(user=self.request.user, category_id=category_id)
    
    # カテゴリ情報をテンプレートに渡す
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        context['category'] = get_object_or_404(InterestCategory, id=category_id)
        return context


# 学習目標の作成
class CreateLearningObjectiveView(LoginRequiredMixin, CreateView):
    model = LearningObjective
    template_name = 'ascension/create_learning_objective.html'
    form_class = CreateLearningObjectiveForm

    # カテゴリ情報をテンプレートに渡す
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        context['category'] = get_object_or_404(InterestCategory, id=category_id)
        return context
    
    # バリデーション成功で保存
    def form_valid(self, form):
        form.instance.user = self.request.user
        category_id = self.kwargs.get('category_id')  # urlからカテゴリidを取得
        form.instance.category = get_object_or_404(InterestCategory, id=category_id)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('ai_support:generate_plan_preview', kwargs={'learning_objective_id': str(self.object.id)})
    

ascension/templates/ascension/add_interest_category.html
{% extends "ascension/base.html" %}
{% load static %}

{% block title %}興味分野追加{% endblock title %}

{% block contents %}
<div class='container d-flex justify-content-center'>
    <div class='col-12 col-md-7'>
        <div class='row text-center'>
            <h1>興味分野の追加</h1><br>
        </div>
        <form method='POST' action="{% url 'ascension:add_interest_category' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class='btn btn-primary'>追加</button>
        </form>
    </div>
</div>
{% endblock contents %}

ascension/templates/ascension/base.html
{% load static %}

<html lang='ja'>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />

        <!--My Style-->
        <link rel="stylesheet" type='text/css' href="{% static "css/mystyle.css" %}">
        {% block head %}{% endblock head %}
    </head>
    <body id='page-top'>
        <div id='wrapper'>
            <!-- Navigation-->
            <a class="menu-toggle rounded d-flex align-items-center justify-content-center" href="#"><i class="fas fa-bars"></i></a>
            <nav id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand"><a href="#page-top">ASCENSION</a></li>
                    <li class="sidebar-nav-item"><a href="{% url 'ascension:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li class="sidebar-nav-item"><a href="{% url 'ascension:interest_category_list' %}">カテゴリ画面</a></li>
                        <li class="sidebar-nav-item"><a href="#services">お気に入り</a></li>
                        <li class="sidebar-nav-item"><a href="{% url 'account_logout' %}">ログアウト</a></li>
                    {% else %}
                        <li class='sidebar-nav-item'><a href="{% url 'account_login' %}">ログイン</a></li>
                        <li class='sidebar-nav-item'><a href="{% url 'account_signup' %}">サインアップ</a></li>
                    {% endif %}
                    <li class="sidebar-nav-item"><a href="{% url 'ascension:inquiry' %}" class='nav-link {% block active_inquiry %}{% endblock %}'>問い合わせ</a></li>
                </ul>
            </nav>
            {% block header %}{% endblock header %}
            {% block contents %}{% endblock contents %}
            <!-- Footer-->
            <footer class="footer text-center">
                <div class="container px-4 px-lg-5">
                    <ul class="list-inline mb-5 d-flex justify-content-center">
                        <li class="list-inline-item">
                            <a class="social-link rounded-circle text-white mr-3 d-flex align-items-center justify-content-center" href="#!">
                                <i class="icon-social-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="social-link rounded-circle text-white mr-3 d-flex align-items-center justify-content-center" href="#!">
                                <i class="icon-social-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="social-link rounded-circle text-white d-flex align-items-center justify-content-center" href="#!">
                                <i class="icon-social-github"></i>
                            </a>
                        </li>
                    </ul>
                    <p class="text-muted small mb-0">Copyright &copy; Your Website 2023</p>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src={% static "js/scripts.js" %} defer></script>
    </body>
</html>

ascension/templates/ascension/create_learning_objective.html
{% extends "ascension/base.html" %}

{% block title %}学習目標作成|ASCENSION{% endblock title %}

{% block contents %}
<div class='container d-flex justify-content-center'>
    <div class='col-12 col-md-7'>
        <div class='row text-center'>
            <h1>学習目標の作成</h1><br>
        </div>
        <form method='POST' action="{% url 'ascension:create_learning_objective' category.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class='btn btn-primary'>作成</button>
        </form>
    </div>
</div>
{% endblock contents %}

ascension/templates/ascension/delete_interest_category.html
{% extends "ascension/base.html" %}
{% load static %}

{% block title %}興味分野の削除{% endblock title %}

{% block contents %}
<div class='container'>
    <div class='row text-center'>
        <div class='text-center'>
            <h1>興味分野の削除</h1><br>
        </div>
        <form method='POST' action="{% url 'ascension:delete_interest_category' category.id %}">
            {% csrf_token %}
            <p>
                カテゴリ"<strong>{{ category.name }}</strong>"を削除すると含まれる全ての学習データが削除されます。本当に削除しますか？
            </p>
            <button type='submit' class='btn btn-primary mt-5'>削除</button>
            <a href="{% url 'ascension:interest_category_list' %}" class='btn btn-secondary mt-5'>キャンセル</a>
        </form>
    </div>
</div>
{% endblock contents %}

ascension/templates/ascension/index.html
{% extends "ascension/base.html" %}
{% load static %}

{% block title %}TOP画面|ASCENSION{% endblock title %}
{% block header %}
<!-- Header-->
<header class="masthead d-flex align-items-center">
    <div class="container px-4 px-lg-5 text-center">
        <h1 class="mb-1">ASCENSION</h1>
        <h3 class="mb-5"><em>学習サービス</em></h3>
        {% if user.is_authenticated %}
            <a href="{% url 'ascension:interest_category_list' %}" class='btn btn-primary btn-l'>カテゴリ画面</a>
        {% else %}
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl">LOG IN</a><br>
            <a href="{% url 'account_signup' %}">アカウントを作成しますか？</a>
        {% endif %}
    </div>
</header>
{% endblock header %}
{% block contents %}
<!-- Services-->
<section class="content-section bg-primary text-white text-center" id="services">
    <div class="container px-4 px-lg-5">
        <div class="content-section-heading">
            <h3 class="text-secondary mb-0">Services</h3>
            <h2 class="mb-5">What We Offer</h2>
        </div>
        <div class="row gx-4 gx-lg-5">
            <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                <span class="service-icon rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center">
                    <i class="icon-screen-smartphone"></i>
                </span>
                <h4><strong>学習プラン生成</strong></h4>
                <p class="text-faded mb-0">Looks great on any screen size!</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                <span class="service-icon rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center">
                    <i class="icon-pencil"></i>
                </span>
                <h4><strong>ハンズオン学習</strong></h4>
                <p class="text-faded mb-0">Freshly redesigned for Bootstrap 5.</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                <span class="service-icon rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center">
                    <i class="icon-like"></i>
                </span>
                <h4><strong>理解度テスト</strong></h4>
                <p class="text-faded mb-0">
                    Millions of users
                    <i class="fas fa-heart"></i>
                    Start Bootstrap!
                </p>
            </div>
            <div class="col-lg-3 col-md-6">
                <span class="service-icon rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center">
                    <i class="icon-mustache"></i>
                </span>
                <h4><strong>学習管理</strong></h4>
                <p class="text-faded mb-0">I mustache you a question...</p>
            </div>
        </div>
    </div>
</section>
{% endblock contents %}

ascension/templates/ascension/inquiry.html
{% extends "ascension/base.html" %}
{% load django_bootstrap5 %}

{% block title %}問い合わせ{% endblock title %}
{% block active_inquiry %}active{% endblock active_inquiry %}

{% block contents %}
<div class='container d-flex justify-content-center'>
    <div class='col-12 col-md-7'>
        <h1 class='text-center mb-4'>問い合わせ</h1><br>
        <form action="{% url 'ascension:inquiry' %}" method='POST'>
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% bootstrap_form form %}
            <button class='btn btn-primary' type='submit'>送信</button>
        </form>
    </div>
</div>
{% endblock contents %}

ascension/templates/ascension/interest_category_list.html
{% extends "ascension/base.html" %}
{% load static %}

{% block title %}興味分野一覧|ASCENSION{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static "css/clean-blog.css" %}">
{% endblock head %}

{% block contents %}
<div class='container px-4 px-lg-5'>
    <div>
        <h1>{{ request.user.username }}の興味分野</h1><br>
    </div>
    <!--カテゴリ削除時にメッセージを表示-->
    {% if messages %}
        <div class=''>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        <br>
    {% endif %}
    <!--興味分野リスト-->
    <div class='justify-content-center'>
        <div class=''>
            {% for category in object_list %}
                <div class='post-preview'>
                    <a href="{% url 'ascension:learning_objective_list' category.id %}">
                        <h3>{{ category.name }}</h3>
                    </a>
                    <a href="{% url 'ascension:delete_interest_category' category.id %}" class='btn btn-danger btn-sm'>削除</a>
                </div>
                <hr>
            {% empty %}
                <p>興味分野がありません。</p>
            {% endfor %}
            <div>
                <a href="{% url 'ascension:add_interest_category' %}" class='btn btn-primary'>追加</a>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

ascension/templates/ascension/learning_objective_list.html
{% extends "ascension/base.html" %}
{% load static %}

{% block title %}学習目標一覧{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static "css/clean-blog.css" %}">
{% endblock head %}

{% block contents %}
<div class='container px-4 px-lg-5'>
    <div class='text-center'>
        <h1>{{ request.user.username }}</h1><br>
        <h2>〜{{ category.name }}の学習目標一覧〜</h2>
    </div>
    <!--学習目標リスト-->
    <div class='justify-content-center'>
        <div>
            {% for learning_objective in learning_objectives %}
                <div class='post-preview'>
                    <a href="" >
                        {{ learning_objective.title }}
                    </a>
                    <a href="#" class='btn btn-danger'>削除</a>
                </div>
                <hr>
            {% empty %}
                <p>学習目標がありません。</p>
            {% endfor %}
            <div>
                <a href="{% url 'ascension:create_learning_objective' category.id %}" class='btn btn-primary'>新規作成</a>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}